services:
  - type: web
    name: feedback-backend
    env: python
    region: singapore
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.10.13
    plan: free

  - type: static
    name: feedback-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
    branch: main
