services:
  - type: web
    name: feedback-backend
    env: python
    plan: free
    region: singapore
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

  - type: web
    name: feedback-frontend
    env: static
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
